version: '3.8'

services:
  # Node 1: Web UI + API Gateway
  web-ui:
    build: ./web-ui
    ports:
      - "3100:80"
    volumes:
      - ./web-ui:/usr/share/nginx/html
    networks:
      - banking-network
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    ports:
      - "3001:3000"
    networks:
      - banking-network
    depends_on:
      - business-logic

  # Node 2: Business Logic
  business-logic:
    build: ./business-logic
    ports:
      - "8000:8000"
    networks:
      - banking-network
    depends_on:
      - data-access

  # Node 3: Data Access Layer
  data-access:
    build: ./data-access
    ports:
      - "8001:8001"
    networks:
      - banking-network
    depends_on:
      - database

  # Node 4: Database
  database:
    build: ./database
    ports:
      - "55432:5432"
    volumes:
      - database_data:/app
    networks:
      - banking-network

  # Node 5: Cache
  cache:
    build: ./cache
    ports:
      - "6379:6379"
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  database_data:

